project:
  name: INEW_GWAS
  random_seed: 42

tools:
  plink: plink
  rscript: Rscript
  awk: awk

resources:
  threads: 8

paths:
  repo_root: ./
  data_root: data
  results_root: results
  scripts_root: scripts

inputs:
  genotypes_prefix: genotypes/raw_genotypes.csv
  phenotypes_file: phenotypes/wp_pheno_results.txt
  metadata_file: metadata/35k_probe_set_IWGSCv1.xlsx
  references_dir: references

outputs:
  tables_dir: results/tables
  figures_dir: results/figures
  ibs_dir: results/IBS
  ld_decay_dir: results/ld_decay
  pruned_dir: results/pruned_data
  plink_fmt_dir: results/plink_format

plink_defaults:
  mind: 0.1
  geno: 0.1
  maf: 0.05
  hwe: 1e-6
